runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: .*
  script: main.api

libraries:
- name: MySQLdb
  version: "latest"
- name: webapp2
  version: "latest"